DudaKristian/DepecheCode

- src/index.html
Перший пішов =)
Додаю шрифти:
- DM Sans (Regular 400, Medium 500, Bold 700)
- Titan One (Regular 400)
> Adds page fonts

- src/sass/utils/variables.scss
Для удобства добавил некоторые описания. Все цвета получат свои описания по мере того как мы будет присваивать классы в html разметке.
> Файл, хранящий переменные палитры.

- src/index.html
- src/index.js
Додаю index.js в src
Розкомітив скрипт в index.html
> Fixes autocompiler

- src/sass/base/_reset.scss
Забираєм маркери зі списків і підкреслення з посилань
> Adds reset 2.0

- src/sass/base/_base.scss
- src/sass/main.scss
Создан и импортирован файл _base.scss. В него добавлен класс "semantical", предназначающийся для скрытия обязательных семантических заголовков 2го уровня, после тега <section>.
> Создан и импортирован файл _base.scss.

- src/partials/products.html
HTML разметка секции products, в файле partials/products.html. Вписаны и адаптированы изображения под разную плотность и размер view port.
> Разметка секции Products

- src/partials/contacts.html
Зробила розмітку HTML,
заголовок h1 потім сховається
> Contacts.html

- src/partials/footer.html
> footer-html

- src/partials/contacts.html
- src/sass/components/_contacts.scss
В html для кнопок добавила модифікатори, а саме contacts__btn--primary, contacts__btn--secondary, зробила hover, focus.
Якщо все буде правильно, то приступаю до флексів, падінгів і тд (застосовуючи @media)
> Contacts: html, styles

- src/sass/base/_reset.scss
- src/sass/main.scss
- src/sass/utils/variables.scss
Створив змінні шрифтів в variables
Додав основний шрифт в body
Перепідключив variables перед reset
> Adds fonts func

- src/index.html
> Title added

- src/partials/products.html
- src/sass/components/_products.scss
Готовая (надеюсь :D) верстка секции Products. Соблюдены реквесты ТЗ, адаптация под tablet, desktop. Оптимизация и адаптация изображений, как по размеру так и по плотности пикселей. 
Нюансы:
- Кнопка/ссылка со стрелкой: немножко не понятно что да как. В макете все это дело в PNG, ребята все правильно вырезали. Но это никуда не годиться... -Где дизайнер? Вышел из чата. --Ну вы поняли... Таким образом приятный ховер не реализовать. На данном этапе я сделал в виде link с img, в скором найду иконку этой стрелки в SVG (на белоснежных просторах интернета) и сделаю восхитетельную кнопку. По этой же причине не стал адаптировать PNG под размеры и плотность.
- Текст описания... В мобайл в нем больше строк чем на таблетке и десктопе. Из-за чего я сталкивался с тем что нижняя кнопка тупо пробивала …
> "Готовая" секция products.

- src/partials/about.html
- src/partials/advantages.html
- src/sass/components/_about.scss
- src/sass/components/_advantages.scss
стилизировал две секии
добавил картинки псевдоэлементами
> About and Advantages

- src/partials/gallery.html
- src/sass/base/_container.scss
- src/sass/components/_gallery.scss
+ додатковий контейнер спеціально під секцію Gallery
+ градієнт на фоні секції
> Adds gallery styles

- src/sass/components/_contacts.scss
Поставила на кнопки та на силку з телефоном display:block,
after задала: content" > display:block > width:100% > height:1px > bg-c: #e1e1e1. 
Ніяк не виходить зробити відступ від  .contacts__subtext - має бути 25px
І ще помітила, що після кнопки є лінія
> after, button

- src/sass/components/_products.scss
Додав правило font-weight:400;
.prettierrc.yaml попереносив рядки, і деякі обєднав...нічого не поламалось)
> Fixes font-weight (products__item-title)

- src/partials/products.html
- src/sass/components/_products.scss
Додав правило для приховання частини тексту від 768рх
Виправив медіа-правило на 1280рх
> Fixes text

- package-lock.json
- src/partials/about.html
Проверка валидатором сделана, баги исправлениы, было одно предупреждение, что при открытии секции /section> <section class="customer-reviews"> <div необходимо h2-h6 заглавие, а у нас див, этого не исправлял...
> validator check done

- src/partials/products.html
- src/sass/components/_products.scss
Допилены кнопки. Перевел их с link в button, изображение добавил через background. Все адаптировано под размеры и плотность. 
*После того как был добавлен span со скрывающеюся строчкой, на размере 320px было смещено положение кнопки. Исправил. 
P.S. по всем параметрам секция готова.
> Финальная реализация кнопки + bugfix

- src/images/contacts-btn-vector.svg
- src/partials/contacts.html
- src/sass/components/_contacts.scss
Відцентрувала кнопки, афтер виправлений
> Scss, after, button

- src/sass/components/_advantages.scss
Advantages: позиціонування і адаптив
> advantages-adaptive

- src/sass/components/_advantages.scss
> advantages-commit

- src/images/icons.svg
- src/partials/about.html
- src/partials/contacts.html
- src/partials/hero-header.html
- src/sass/base/_base.scss
- src/sass/components/_about.scss
- src/sass/components/_hero-header.scss
Иконки SVG для кнопок в секциях: header, about и contacts. SVG файлы были добавлены в имеющейся спрайт. В файл _base добавлена стилизация иконок.
> Иконки SVG для кнопок

- src/sass/components/_hero-header.scss
D:\Users\Arlth\Documents\GitHub\DepecheCode\src\sass\main.scss:343:14: expected "}".
не работала команда npm run dev
> Fix expected }

- src/index.html
- src/js/products.js
- src/partials/products.html
- src/sass/components/_products.scss
Анимация элементов в секции products: создан контейнер с содержимым. Подключен CDN JQ, скрипт в файле products.js
> Анимация элементов в секции products

- src/sass/components/_hero-header.scss
> анімація картинок hero

- src/partials/about.html
- src/partials/contacts.html
- src/partials/customer-reviews.html
- src/partials/hero-header.html
- src/partials/products.html
> якорні силки

- src/images/icons.svg
- src/images/symbol-defs.svg
- src/index.html
- src/js/mobile-menu.js
- src/partials/hero-header.html
- src/sass/components/_hero-header.scss
> mobile-menu

- src/images/contacts/sprite.svg
- src/partials/contacts.html
- src/sass/components/_contacts.scss
тільки для однієї кнопки contacts__btn--secondary
> Модальне вікно

- src/partials/hero-header.html
- src/sass/components/_hero-header.scss
Переробив батони в посилання і змінив margin-right в десктопній версії
> Try number 2...buttons->a

- src/partials/about.html
- src/partials/hero-header.html
- src/sass/base/_base.scss
- src/sass/components/_contacts.scss
- src/sass/components/_hero-header.scss
Фикс стрелки в кнопхах хедера и about. 
Фикс круглой кнопки со стрелокой в хедере, расположение и адаптив
> Фикс SVG иконок и кнопки в хедере

- src/js/mobile-menu.js
- src/partials/hero-header.html
Добавлена функция которая скрывает меню после перехода на секцию. 
При нажатии на ссылку home страница больше не перезапускается а возвращается в топ. (Это можно было реализовать и якорем, но я сделал через JQ)
> Фикс меню на mobile

- src/js/mobile-menu.js
Мешал  всему скрипт, который не позволяет прокручивать страницу пока открыто меню. Решил просто убрав его.
> Фикс скролла

- src/js/mobile-menu.js
- src/partials/hero-header.html
> Финальный фикс якорей

- src/sass/components/_contacts.scss
> Adds linear-gradient on "Contacts" background

- src/partials/hero-header.html
- src/sass/components/_hero-header.scss
фікс ширини хедера костильом.
Взяв хедер в дів, йоу задав центрування, макс ширину і position:relative
> header width\fix

- src/sass/components/_products.scss
Вроде как сделал правки указанные по видео
> Правки по видео

- src/index.html
- src/js/mobile-menu.js
- src/js/scroll-btn.js
- src/partials/hero-header.html
- src/sass/base/_base.scss
Добавлена кнопка, стили в Base и отдельный файл js под ее скрипт
> Добавлена кнопка которая возвращает пользователя в самый верх

- src/sass/components/_hero-header.scss
- src/sass/components/_mobile-menu.scss
> header-commit-adaptive

- src/sass/components/_gallery.scss
> Adds cursor: pointer:

- src/sass/components/_contacts.scss
Повертаю background секції Contacts
> Adds  linear-gradient on Contacts background #2
